### ISSUE TITLE
How many GPUs are "allowed"?

### ISSUE THREAD

**Issue by Marcophono2** [paulcjh/gpt-j-6b#2]
Paul, thank you very much for your efforts! I am looking for a quick way just to make my own tests on a local machine with GPT-J and your project seems to be the very best. Still not set up but thank you in advance!
I only need the prediction function.
Just a question to the hardware setup: You wrote that this works on AWS T4 instances. But on the AWS description website 
https://aws.amazon.com/ec2/instance-types/?nc1=h_ls T4g (not T4) obviously is only cpu based. On the other hand side G4dn (described on the same website) seems to be the right one. Is that correct?
And: Does your script works only with one GPU or is the amount of GPUs in any matter? Anywhere I read that only 4 GPUs are supported, not more, not less. But that could have been on another project website. I read too much today to sort it clearly. :)

Every recommendation which AWS setup I shall/can use for my porposes is very appreciated.

Best regards
Marc

P.S.: Another question by the way: Everywhere is written that the "pile" as the text sorce is only english text. But how can it be that prompts with german text output good results also in german text?

**Comment by paulcjh** [comment]
@Marcophono2 Ahh sorry I should have been more explicit, yes it's running on g4dn GPUs.

This script is for running on a single GPU at the moment.
I do recommend the standard g4dn instances, but it really depends upon you specific use case. We do offer simply the prediction setup here: https://hub.getneuro.ai/model/nlp/gpt-j-6B-text-generation in a simple pay for what you use API.

On you last point I'm not 100% sure what you're asking. Have you tried inputting German yet? It might very well be the case that you'll need to fine tune the model to learn German, although that wouldn't really be fine tuning it would be a very large rewrite of the model weights taking a lot of training. The tokeniser would also have to support German, have you looked into this with regards to the tokeniser?

**Comment by zaptrem** [comment]
> @Marcophono2 Ahh sorry I should have been more explicit, yes it's running on g4dn GPUs.
> 
> This script is for running on a single GPU at the moment.
> I do recommend the standard g4dn instances, but it really depends upon you specific use case. We do offer simply the prediction setup here: https://hub.getneuro.ai/model/nlp/gpt-j-6B-text-generation in a simple pay for what you use API.
> 
> On you last point I'm not 100% sure what you're asking. Have you tried inputting German yet? It might very well be the case that you'll need to fine tune the model to learn German, although that wouldn't really be fine tuning it would be a very large rewrite of the model weights taking a lot of training. The tokeniser would also have to support German, have you looked into this with regards to the tokeniser?

What are the VRAM requirements for single GPU inference? Could I use this script to run GPT-j inference on my 10gb VRAM RTX 3080? If not, do you have any suggestions on where to look for that? 

Thanks!
