### ISSUE TITLE
Why is vocab 50400 rather than 50257 like the GPT2 tokenizer?

### ISSUE THREAD

**Issue by mallorbc** [paulcjh/gpt-j-6b#3]
Listed here https://github.com/kingoflolz/mesh-transformer-jax  we can see that the n_vocab is 50257.  However, the output of this model is 50400.  Why is this?

**Comment by andreamad8** [comment]
Yes, I found out the same problem. And this is especially troublesome when loading the model after fine-tuning. Any solution?

**Comment by mallorbc** [comment]
@andreamad8 I have successfully fine-tuned gpt-j-6B.  I ran into the same issue you did.  My issue was I was resizing the model based on the size of the GPT 2 tokenizer. Do not do that.

**Comment by andreamad8** [comment]
thanks :)

**Comment by mallorbc** [comment]
Gonna close this out.  Apparently, the reason is to give ample space to add more tokens.  Just make sure that you don't resize the output layer and things should work fine
